from enum import Enum


class NodeType(Enum):
    DATA_STRUCTURE = 'DATA_STRUCTURE'
    DECLARATION = 'DECLARATION'

    SEQUENCE_DECLARATION = 'SEQUENCE_DECLARATION'

    CHOICE_DECLARATION = 'CHOICE_DECLARATION'
    CHOICE_ATTRIBUTE = 'CHOICE_ATTRIBUTE'

    ARRAY_DECLARATION = 'ARRAY_DECLARATION'

    ARGUMENTS = 'ARGUMENTS'
    ARGUMENT = 'ARGUMENT'

    ATTRIBUTE = 'ATTRIBUTE'

    TYPE = 'TYPE'
    SIMPLE_TYPE = 'SIMPLE_TYPE'
    SIMPLE_TYPE_PARAMETRIZED = 'SIMPLE_TYPE_PARAMETRIZED'
    DECLARED_TYPE = 'DECLARED_TYPE'

    PARAMETERS = 'PARAMETERS'
    PARAMETER = 'PARAMETER'

    OR_EXPRESSION = 'OR_EXPRESSION'
    AND_EXPRESSION = 'AND_EXPRESSION'
    SIMPLE_EXPRESSION = 'SIMPLE_EXPRESSION'
    RELATIONAL_OPERATOR = 'RELATIONAL_OPERATOR'

    VALUE = 'VALUE'

    BOOLEAN = 'BOOLEAN'
    NUMBER = 'NUMBER'
    IDENTIFIER = 'IDENTIFIER'
